about/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.about, name='about'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.contact, name='contact'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.new, name='new'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

about/models.py
from django.db import models

contact/models.py
from django.db import models

news/models.py
from django.db import models
from datetime import datetime

class Article(models.Model):
    article_title = models.CharField('название статьи', max_length=200)
    article_text = models.TextField('текст статьи', default="")
    pub_date = models.DateTimeField('дата публикации')
    article_image = models.ImageField('изображение', upload_to='news_images/', default="None")

    def __str__(self):
        return self.article_title

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length = 100)
    comment_text = models.TextField('текст комментария', max_length=1000)
    comment_date = models.DateTimeField('дата комментария', default=datetime.now)

    def __str__(self):
        return self.author_name

about/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about/aboutPage.html')

contact/views.py
from django.shortcuts import render

def contact(request):
    return render(request, 'contact/contactPage.html')

home/views.py
from django.shortcuts import render
from news.models import Article

def index(request):
    latest_articles = Article.objects.order_by('-pub_date')[:3]
    return render(request, 'home/homePage.html', locals())

news/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import *
from django.core.paginator import Paginator
from django.db.models import Q


def new(request):
    search_query = request.GET.get('search', '')
    if search_query:
        articles_list = Article.objects.filter(Q(article_title__icontains=search_query) | Q(article_text__icontains=search_query))
    else:
        articles_list = Article.objects.order_by('-pub_date')

    paginator = Paginator(articles_list, 10)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    }
    return render(request, 'news/newsPage.html', context=context)


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")
    comments_list = a.comment_set.order_by('-id')
    sum_com = Comment.objects.filter(article_id=a).count()
    return render(request, 'news/detail.html', {'article': a, 'comments_list': comments_list, 'sum_com':sum_com})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('news:detail', args=(a.id,)))

templates/about/aboutPage.html
{% extends "base.html" %}
{% load static %}

{% block title %}
 О сайте
{% endblock %}

{% block content %}
    <div class="container-fluid pt-5">
        <div class="container text-center p-2">
            <h1 class="p-5">На сайте публикуются футбольные новости:</h1>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Топовые европейские чемпионаты</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/topliga.jpeg' %}" height="100px" width="170px">
                </div>
            </div>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Лига чемпионов</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/ligachemp.jpg' %}" height="100px" width="170px">
                </div>
            </div>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Лига Европы</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/ligaeuro.jpeg' %}" height="100px" width="170px">
                </div>
            </div>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Чемпионат мира</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/worldcup.jpeg' %}" height="100px" width="170px">
                </div>
            </div>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Чемпионат Европы</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/eurocup.jpg' %}" height="100px" width="170px">
                </div>
            </div>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Лига наций</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/liganations.jpg' %}" height="100px" width="170px">
                </div>
            </div>
            <div class="row" style="margin-bottom: 30px; font-size: 25px">
                <div class="col-6 my-auto text-center font-italic">
                    <p>- Трансферы</p>
                </div>
                <div class="col-6 text-left">
                    <img src="{% static 'media/images/transfers.jpg' %}" height="100px" width="170px">
                </div>
            </div>

        </div>
    </div>
    <br>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
 <div class="wrapper">
 {% include 'navbar.html' %}
     <div class="wrapper-content">

        {% block content %}
        {% endblock %}

      </div>
 {% include 'footer.html' %}
 </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/contact/contactPage.html
{% extends "base.html" %}
{% load static %}

{% block title %}
 Контакты
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="container">
            <div class="row p-5">
                <div class="col-md-6 text-center">
                    <h2>Контакты</h2><br>
                    <p><b style="font-size: large">Адрес:</b> г. Харьков, ул. Сумская 1</p>
                    <p><b style="font-size: large">Телефон:</b> +380990990990</p>
                    <p><b style="font-size: large">Email:</b> example@gmail.com</p>
                </div>
                <div class="col-md-6 text-center">
                    <h2>Местоположение на карте</h2><br>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2564.9467697291307!2d36.22974931528572!3d49.99360742805823!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4127a0f003880a0f%3A0x72072c3abf395115!2z0YPQuy4g0KHRg9C80YHQutCw0Y8sIDEsINCl0LDRgNGM0LrQvtCyLCDQpdCw0YDRjNC60L7QstGB0LrQsNGPINC-0LHQu9Cw0YHRgtGMLCDQo9C60YDQsNC40L3QsCwgNjEwMDA!5e0!3m2!1sru!2scz!4v1575209128471!5m2!1sru!2scz" height="300" frameborder="0" style="max-width:100% border:0;" allowfullscreen=""></iframe>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/footer.html
{% load static %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<footer class="page-footer font-small unique-color-dark">

  <div style="background-color: #666666; color: white">
    <div class="container">
      <div class="row py-4 d-flex align-items-center">
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0" style="font-size: large">Мы в социальных сетях:</h6>
        </div>
        <div class="col-md-6 col-lg-7 text-center text-md-right">
            <div class="text-center center-block">
                    <a target="_blank" style="color: white; padding-right: 10px" href="https://www.facebook.com/"><i class="fa fa-facebook-square fa-3x social"></i></a>
                    <a target="_blank" style="color: white; padding-right: 10px" href="https://twitter.com/"><i class="fa fa-twitter-square fa-3x social"></i></a>
                    <a target="_blank" style="color: white; padding-right: 10px" href="https://www.youtube.com/"><i class="fa fa-youtube-square fa-3x social"></i></a>
                    <a target="_blank" style="color: white; padding-right: 10px" href="mailto:example@gmail.com"><i class="fa fa-envelope-square fa-3x social"></i></a>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-copyright text-center py-3" style="background-color: #464646; color: white">© 2019 Все права защищены</div>

</footer>

templates/home/homePage.html
{% extends "base.html" %}
{% load static %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="section-top">
        <img src="{% static 'media/images/man.jpg' %}" width="100%">
    </div>
    <br/>
    <h1 class="text-center font-italic text-uppercase">футбольные новости</h1>
    <br/>
    <div class="section">
        <div class="container">
            <div class="row">
                {% for article in latest_articles %}
                    <div class="col-lg-4">
                    <div class="card text-center" style="background-color: #e3e4e6">
                        <img class="card-img-top" src="{{ article.article_image.url }}" height="200px" alt="">
                        <div class="card-body">
                            <h4 class="card-title">{{article.article_title}}</h4>
                            <div class="row">
                                <div class="col-sm-6">
                                    <em>{{ article.pub_date }}</em>
                                </div>
                                <div class="col-sm-6">
                                    <a href="{%  url 'news:detail' article.id %}" class="btn btn-primary">Подробнее</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br/>
    <h4 class="text-center"><a href="{% url 'news:new' %}" class="btn btn-success" role="button">Все новости</a></h4>
    <br/>
{% endblock %}

templates/navbar.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img id="f" title="Главная" src="https://us.123rf.com/450wm/photoart23d/photoart23d1705/photoart23d170500507/79285197-las-luces-de-ne%C3%B3n-de-la-letra-f-indicaron-aislado-en-fondo-negro.jpg?ver=6" width="35px" height="35px" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'news:new' %}">Новости</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">О сайте</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Контакты</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'news:new' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search" name="search">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Найти</button>
        </form>
    </div>
</nav>

templates/news/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ article.article_title }}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="container text-center">
            <br/><h1>{{ article.article_title }}</h1><br>
            <em>{{ article.pub_date }}</em><br><br>
            <img src="{{ article.article_image.url }}" style="max-width: 100%" height="auto"/><br><br>
            <article class="text-left" style="font-size: large; white-space: pre-wrap">{{ article.article_text }}</article>
        </div>
    </div>

    <hr>

    <div class="container-fluid">
        <h3>Комментарии ({{ sum_com }})</h3><br>
        <form action="{% url 'news:leave_comment' article.id %}" method="POST">
            {% csrf_token %}
            <input type="text" required placeholder="Ваше имя" name="name"><br><br>
            <textarea name="text" required placeholder="Текст комментария" cols="30" rows="5" wrap="soft"></textarea><br>
            <button type="submit">Оставить комментарий</button>
        </form>
    </div>

    <hr>
    <div class="container-fluid">
        {% for c in comments_list %}
            <p>
                <strong style="font-size: large">{{ c.author_name }}</strong>
                <p>{{ c.comment_text }}</p>
                <em style="font-size: small">{{ c.comment_date }}</em>
            </p>
            <hr/>
        {% endfor %}
    </div>
{% endblock %}

templates/news/newsPage.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Новости
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="container p-2">
            <div class="row">
            {% for a in page_object.object_list %}
                <div class="col-md-6">
                <div class="card text-center mx-auto m-4" style="background-color: #e3e4e6; width: 25rem">
                    <img class="card-img-top" src="{{ a.article_image.url }}" height="220px" alt="">
                    <div class="card-body">
                    <h4 class="card-title">{{a.article_title}}</h4>
                        <div class="row">
                            <div class="col-sm-6">
                                <em>{{ a.pub_date }}</em>
                            </div>
                            <div class="col-sm-6">
                                <a href="{%  url 'news:detail' a.id %}" class="btn btn-primary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                <br>
            {% endfor %}
            </div>
        </div>
    </div>
    <br>

    {% if is_paginated %}
        <nav aria-label="...">
          <ul class="pagination justify-content-center">
            <li class="page-item {% if not prev_url %} disabled {% endif %}">
              <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Previous</a>
            </li>

            {% for n in page_object.paginator.page_range %}
                {% if page_object.number == n %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
                    </li>
                {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                </li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not next_url %} disabled {% endif %}">
              <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Next</a>
            </li>
          </ul>
        </nav>
    {% endif %}
    <br>

{% endblock %}